skip-check:
  - CKV_AWS_18  
  - CKV_AWS_144
  - CKV_AWS_145  
  - CKV2_AWS_5   
  - CKV2_AWS_61  
  - CKV2_AWS_62  
  
directory:
  - environments/dev
  - environments/prod
external-checks-dir:
  - policies/checkov
framework:
  - terraform
compact: true
soft-fail: false
